---
title: "UOK Public Data Analysis"
output: rmdformats::readthedown
---

# 1. Dependancies 

```{r}
library(rmdformats) #library for nice html output of notebooks
library(DESeq2) # diff. expr. analysis tools
library(tidyverse) # library for data science operations
library(pheatmap) # data vis
library(RColorBrewer) # RColorBrewer gives us colors with which to plot things
library(gplots) # library for enhanced versions of standard plots
library(gprofiler2) # used to call ensembl database
library(genefilter) # library to filter genes from high-throughput experiments
library(gprofiler2) # library for functional enrichment analysis
library(ggpubr) # library for making publication quality plots
library(ComplexHeatmap) # library for making genomic heatmaps
library(circlize) # library for circular layout generation
library(EnhancedVolcano) # enhanced volcano plots
```

```{r}
theme_set(theme_classic())
setwd("/Users/maligireddyss/Documents/UOK_public_data")
```

# 2. Processing Input Data

## 2.1 Importing HTSEQ-COUNT data 

```{r}
coldata1 <- read.csv("HLRCCRunTable.csv", header = TRUE, sep = ",")
coldata2 <- read.csv("HLRCCRunTable_test1.csv", header = TRUE, sep = ",")
```

```{r}

directory1 <- "/Users/maligireddyss/Documents/UOK_public_data/new_counts"
directory2 <- "/Users/maligireddyss/Documents/UOK_public_data/counts"

dds1 <- DESeqDataSetFromHTSeqCount(coldata1, directory = directory1,
 ~Tissue_type_details, ignoreRank = FALSE)

dds2 <- DESeqDataSetFromHTSeqCount(coldata2, directory = directory2,
 ~Tissue_type_details, ignoreRank = FALSE)

#creates a DESeq object from HTSeq count files
#went through and added an extra column to the start of the metadata file
#added .txt to samples so that the directory is read correctly
```

# 3. Quality Control Plots / Data Formatting
## 3.1 Quality Control Cleaning
```{r}

dds1 <- na.omit(dds1)
nrow(dds1)
dds1 <- dds1[rowSums(counts(dds1)) > 1, ]
nrow(dds1)

nrow(dds2)
dds2 <- dds2[rowSums(counts(dds2)) > 1, ]
nrow(dds2)

# this chunk removes empty counts
# 
```

## 3.2 VST and Rlog plots
```{r}
rld1 <- rlog(dds1, blind = FALSE)
head(assay(rld1), 3)

vsd1 <- vst(dds1, blind = FALSE)
head(assay(vsd1), 3)

df1 <- bind_rows(
    as_tibble(assay(vsd1)[, 1:2]) %>% mutate(transformation = "vst1"),
    as_tibble(assay(rld1)[, 1:2]) %>% mutate(transformation = "rlog1"))
colnames(df1)[1:2] <- c("x", "y")

ggplot(df1, aes(x = x, y = y)) + geom_hex(bins = 80) +
    coord_fixed() + facet_grid(. ~ transformation)

rld2 <- rlog(dds2, blind = FALSE)
head(assay(rld2), 3)

vsd2 <- vst(dds2, blind = FALSE)
head(assay(vsd2), 3)

df2 <- bind_rows(
    as_tibble(assay(vsd2)[, 1:2]) %>% mutate(transformation = "vst2"),
    as_tibble(assay(rld2)[, 1:2]) %>% mutate(transformation = "rlog2"))
colnames(df2)[1:2] <- c("x", "y")

ggplot(df2, aes(x = x, y = y)) + geom_hex(bins = 80) +
    coord_fixed() + facet_grid(. ~ transformation)




```

## 3.2 PCA

```{r}
plotPCA(vsd1, "Tissue_type_details")
plotPCA(vsd2, "Tissue_type_details")
plotPCA(vsd1, "Patient")
plotPCA(vsd1, "gender")
```

##3.3 Heatmap

```{r}
sampleDists <- dist(t(assay(vsd1)))

sampleDistMatrix <- as.matrix(sampleDists)
colnames(sampleDistMatrix) <- NULL
colors <- colorRampPalette(rev(brewer.pal(11, "Spectral")))(255)
pheatmap(sampleDistMatrix,
         clustering_distance_rows = sampleDists,
         clustering_distance_cols = sampleDists,
         col = colors,
         show_rownames = TRUE)
```

## 4 DESeq2 Analysis

```{r}
dds1$Tissue_type_details <- relevel( dds1$Tissue_type_details, "Renal Cortex")

dds1 <- DESeq(dds1)

res1 <- results(dds1, contrast = c("Tissue_type_details", "HLRCC Tumor", "Renal Cortex"))

res2 <- results(dds1, contrast = c("Tissue_type_details", "HLRCC Metastasis", "Renal Cortex"))

res3 <- results(dds1, contrast = c("Tissue_type_details", "HLRCC Metastasis", "HLRCC Tumor"))


```

```{r}
plotMA(res1, ylim = c(-25,25))
plotMA(res2, ylim = c(-25,25))
plotMA(res3, ylim = c(-25,25))
```

```{r}
EnhancedVolcano(res1,
                lab = rownames(res1),
                x = "log2FoldChange",
                y = "pvalue",
                title = "HLRCC Tumor v. Renal Cortex",
                ?SelectLab)

EnhancedVolcano(res2,
                lab = rownames(res2),
                x = "log2FoldChange",
                y = "pvalue",
                title = "HLRCC Metastasis v. Renal Cortex",
                ?SelectLab)

EnhancedVolcano(res3,
                lab = rownames(res3),
                x = "log2FoldChange",
                y = "pvalue",
                title = "HLRCC Metastasis v. HLRCC Tumor",
                ?SelectLab)
```
```{r}
topVarGenes <- head( order( rowVars( assay(rld)), decreasing = TRUE), 100)

heatmap.2(assay(rld)[topVarGenes,], scale="row",
          trace="none", dendrogram = "column", margin=c(10, 10),
          main = "Gene Variance in HLRCC",
          col = colorRampPalette(rev(brewer.pal(11, "PuOr")))(255))
```

## 5 Annotation


```{r}
# This section will allow us to sort and export the data as a table
res1Ordered <- res1[order(res1$padj),]
res1OrderedDF <- as.data.frame(res1Ordered)


# Now we're going to use the gprofiler library to assign gene names to the data. Right now, all we have is the big long ENSG ID number
res1OrderedDF_v2 <- res1OrderedDF %>%
  rownames_to_column('ENSG_ID')

res1OrderedDF_v2$ENSG_ID = sub("\\..*","",res1OrderedDF_v2$ENSG_ID)

# Get the names from a gProfiler query
res1Ordered_name <- gconvert(res1OrderedDF_v2$ENSG_ID, organism = "hsapiens", target = "HGNC", filter_na = F) %>%
  dplyr::select(input, name) %>%
  dplyr::rename(ENSG_ID = input, gene_name = name) # change input to ENSG_ID

# Join names dataframe to resOrdered df by the common column of ENSG_ID
res1_export <- inner_join(res1Ordered_name, res1OrderedDF_v2, by = "ENSG_ID")

write.csv(res1_export, file="HLRCC_Tumor_v_Renal_Cortex.csv")

# This section will allow us to sort and export the data as a table
res2Ordered <- res2[order(res2$padj),]
res2OrderedDF <- as.data.frame(res2Ordered)


# Now we're going to use the gprofiler library to assign gene names to the data. Right now, all we have is the big long ENSG ID number
res2OrderedDF_v2 <- res2OrderedDF %>%
  rownames_to_column('ENSG_ID')

res2OrderedDF_v2$ENSG_ID = sub("\\..*","",res2OrderedDF_v2$ENSG_ID)

# Get the names from a gProfiler query
res2Ordered_name <- gconvert(res2OrderedDF_v2$ENSG_ID, organism = "hsapiens", target = "HGNC", filter_na = F) %>%
  dplyr::select(input, name) %>%
  dplyr::rename(ENSG_ID = input, gene_name = name) # change input to ENSG_ID

# Join names dataframe to resOrdered df by the common column of ENSG_ID
res2_export <- inner_join(res2Ordered_name, res2OrderedDF_v2, by = "ENSG_ID")

write.csv(res2_export, file="HLRCC_Metastasis_v_Renal_Cortex.csv")

# This section will allow us to sort and export the data as a table
res3Ordered <- res3[order(res3$padj),]
res3OrderedDF <- as.data.frame(res3Ordered)


# Now we're going to use the gprofiler library to assign gene names to the data. Right now, all we have is the big long ENSG ID number
res3OrderedDF_v2 <- res3OrderedDF %>%
  rownames_to_column('ENSG_ID')

res3OrderedDF_v2$ENSG_ID = sub("\\..*","",res3OrderedDF_v2$ENSG_ID)

# Get the names from a gProfiler query
res3Ordered_name <- gconvert(res3OrderedDF_v2$ENSG_ID, organism = "hsapiens", target = "HGNC", filter_na = F) %>%
  dplyr::select(input, name) %>%
  dplyr::rename(ENSG_ID = input, gene_name = name) # change input to ENSG_ID

# Join names dataframe to resOrdered df by the common column of ENSG_ID
res3_export <- inner_join(res3Ordered_name, res3OrderedDF_v2, by = "ENSG_ID")

write.csv(res3_export, file="HLRC_Metastasis_v_HLRCC_Tumor.csv")

```

```{r}

topVarGenes <- head( order( rowVars( assay(rld1)), decreasing = TRUE), 250)

heatmap.2(assay(rld1)[topVarGenes,], scale="row",
          trace="none", dendrogram = "column", margin=c(10, 10),
          main = "Gene Variance in HLRCC",
          col = colorRampPalette(rev(brewer.pal(11, "PuOr")))(255))

```
```{r}
ggplot(data= res1OrderedDF_v2, aes(x=log2FoldChange, y=-log10(padj))) + 
  geom_point(aes(color=padj < 0.05)) + 
  ggtitle("HLRCC Tumor vs Renal Cortex") +
  xlab("log2 Fold Change") + ylab("-log10 padj")

ggplot(data= res2OrderedDF_v2, aes(x=log2FoldChange, y=-log10(padj))) + 
  geom_point(aes(color=padj < 0.05)) + 
  ggtitle("HLRCC Metastasis vs Renal Cortex") +
  xlab("log2 Fold Change") + ylab("-log10 padj")

ggplot(data= res3OrderedDF_v2, aes(x=log2FoldChange, y=-log10(padj))) + 
  geom_point(aes(color=padj < 0.05)) + 
  ggtitle("HLRCC Metastasis vs HLRCC Tumor") +
  xlab("log2 Fold Change") + ylab("-log10 padj")
```
```{r}
EnhancedVolcano(res1_export,
                lab = res1_export$gene_name,
                x = "log2FoldChange",
                y = "padj",
                pCutoffCol = "padj",
                title = "HLRCC Tumor v. Renal Cortex",
                #selectLab = c('MYC','FH','IGFBP3','VIM','METTL3','METTL14','FTO','ALKBH5','YTHDF2','ALKBH8'),
                labSize=4.0
                )

EnhancedVolcano(res2_export,
                lab = res2_export$gene_name,
                x = "log2FoldChange",
                y = "padj",
                pCutoffCol = "padj",
                title = "HLRCC Metastasis v. Renal Cortex",
                #selectLab = c('MYC','FH','IGFBP3','VIM','METTL3','METTL14','FTO','ALKBH5','YTHDF2','ALKBH8'),
                labSize=4.0
                )

EnhancedVolcano(res3_export,
                lab = res3_export$gene_name,
                x = "log2FoldChange",
                y = "padj",
                title = "HLRCC Metastasis v. HLRCC Tumor",
                #selectLab = c('MYC','FH','IGFBP3','VIM','METTL3','METTL14','FTO','ALKBH5','YTHDF2','ALKBH8'),
                labSize=4.0
                )

```



