# QNB analysis of peaklist that has been pre-filtered by DEseq2 
# Christina Fitzsimmons
# Last updated 2021-04-07


# Set working directory 
setwd("/Users/fitzsimmonscm/Documents/Projects_and_Data/Batista_Lab/FH_SDHB_Project/Rprojects/UOK_manuscript/m6A_IP/")

library(tidyverse)
library(QNB)
library(DESeq2)

# Note: QNB does not like normalized counts
# I am using the normalized peak list of approx 17000 peaks to "filter" the rows for raw counts of QNB
# This list of raw counts will then be used in QNB analysis using standard "per-condition" parameters

# Importing the filtered peak list generated by DESeq2
peaklist_deseq_2count <- read.delim(file = "./06_differential_peak_analysis/2021.04.06_normalized_counts_FALSE-table.csv", 
                                    header = TRUE, sep = ",") %>%
  dplyr::rename(peakID = X)

read_count_file <- function(filepath) {
  data <- read.delim(filepath, sep = "\t", header=FALSE) %>%
    dplyr::rename(peak_ID = V1, raw_counts = V2) %>%
    column_to_rownames(var = "peak_ID")
  return(data)
}


# Read in the raw count files from htseq-count union
# Read in the input count files from htseq
WT1_input <-read_count_file(filepath ="./05_read_counting/peak_level_counts/2021.04.05/BC02.strand-yes.count") %>% dplyr::rename(wt1_input= raw_counts)
WT2_input <-read_count_file(filepath ="./05_read_counting/peak_level_counts/2021.04.05/BC04.strand-yes.count") %>% dplyr::rename(wt2_input = raw_counts)
WT3_input <-read_count_file(filepath ="./05_read_counting/peak_level_counts/2021.04.05/BC05.strand-yes.count")%>% dplyr::rename(wt3_input = raw_counts)
Mut1_input <- read_count_file(filepath ="./05_read_counting/peak_level_counts/2021.04.05/BC06.strand-yes.count") %>% dplyr::rename(mut1_input = raw_counts)
Mut2_input <- read_count_file(filepath ="./05_read_counting/peak_level_counts/2021.04.05/BC07.strand-yes.count") %>% dplyr::rename(mut2_input = raw_counts)
Mut3_input <- read_count_file(filepath ="./05_read_counting/peak_level_counts/2021.04.05/BC12.strand-yes.count") %>% dplyr::rename(mut3_input = raw_counts)

# Read in the IP count files from htseq
WT1_IP <- read_count_file(filepath ="./05_read_counting/peak_level_counts/2021.04.05/BC13.strand-yes.count") %>% dplyr::rename(wt1_IP = raw_counts)
WT2_IP <- read_count_file(filepath ="./05_read_counting/peak_level_counts/2021.04.05/BC14.strand-yes.count") %>% dplyr::rename(wt2_IP = raw_counts)
WT3_IP <- read_count_file(filepath ="./05_read_counting/peak_level_counts/2021.04.05/BC15.strand-yes.count")%>% dplyr::rename(wt3_IP = raw_counts)
Mut1_IP <- read_count_file(filepath ="./05_read_counting/peak_level_counts/2021.04.05/BC16.strand-yes.count") %>% dplyr::rename(mut1_IP = raw_counts)
Mut2_IP <- read_count_file(filepath ="./05_read_counting/peak_level_counts/2021.04.05/BC18.strand-yes.count") %>% dplyr::rename(mut2_IP = raw_counts)
Mut3_IP <- read_count_file(filepath ="./05_read_counting/peak_level_counts/2021.04.05/BC19.strand-yes.count") %>% dplyr::rename(mut3_IP = raw_counts)


# Merging the raw input files into a single list
# filtering the data based on the peak list used by DEseq2
full_data <- bind_cols(WT1_input, WT2_input, WT3_input, Mut1_input, Mut2_input, Mut3_input, WT1_IP, WT2_IP, WT3_IP, Mut1_IP, Mut2_IP, Mut3_IP) %>%
  rownames_to_column(var = "peakID")

filtered_data <- semi_join(full_data, peaklist_deseq_2count)
nrow(filtered_data)

# subseting the data
mutant_input <- filtered_data %>% dplyr::select(peakID, mut1_input, mut2_input, mut3_input) %>% column_to_rownames(var = "peakID")
mutant_IP <- filtered_data %>% dplyr::select(peakID, mut1_IP, mut2_IP, mut3_IP) %>% column_to_rownames(var = "peakID")

wt_input <- filtered_data %>% dplyr::select(peakID, wt1_input, wt2_input, wt3_input) %>% column_to_rownames(var = "peakID")
wt_IP <- filtered_data %>% dplyr::select(peakID, wt1_IP, wt2_IP, wt3_IP) %>% column_to_rownames(var = "peakID")


# Performing the data analysis with QNB
# Exporting the results
result1 = qnbtest(wt_IP, mutant_IP, wt_input, mutant_input, mode = "per-condition")
write.csv(as.data.frame(result1), file="./06_differential_peak_analysis/2021.04.06_QNB-results_multifactor-prefiltered_2counts-peaklist.csv")
nrow(result1)


